INSERT INTO [PRACTICE3].[Assets] (Asset_Type, AssetSymbol, Asset_Name, Industry)
VALUES 
('Bond', 'HYG', 'iShares iBoxx $ High Yield Corporate Bond ETF', 'Fixed Income'),
('Bond', 'VGLT', 'Vanguard Long-Term Treasury ETF', 'Fixed Income'),
('Commodity', 'GC=F', 'Gold', 'Precious Metals'),
('Commodity', 'CL=F', 'Crude Oil WTI', 'Energy'),
('Commodity', 'NG=F', 'Natural Gas', 'Energy'),
('Commodity', 'SI=F', 'Silver', 'Precious Metals'),
('Equity', 'AAPL', 'Apple Inc.', 'Technology'),
('Equity', 'MSFT', 'Microsoft Corporation', 'Technology'),
('Equity', 'GOOGL', 'Alphabet Inc.', 'Technology'),
('Equity', 'NVDA', 'NVIDIA Corporation', 'Technology'),
('Equity', 'AMD', 'Advanced Micro Devices, Inc.', 'Technology'),
('Equity', 'JPM', 'JPMorgan Chase & Co.', 'Financial Services'),
('Equity', 'BAC', 'Bank of America Corporation', 'Financial Services'),
('Equity', 'GS', 'Goldman Sachs Group, Inc.', 'Financial Services'),
('Equity', 'MS', 'Morgan Stanley', 'Financial Services'),
('Equity', 'C', 'Citigroup Inc.', 'Financial Services'),
('Equity', 'JNJ', 'Johnson & Johnson', 'Healthcare'),
('Equity', 'PFE', 'Pfizer Inc.', 'Healthcare'),
('Equity', 'MRK', 'Merck & Co., Inc.', 'Healthcare'),
('Equity', 'ABBV', 'AbbVie Inc.', 'Healthcare'),
('Equity', 'GILD', 'Gilead Sciences, Inc.', 'Healthcare'),
('Equity', 'AMZN', 'Amazon.com, Inc.', 'Consumer Discretionary'),
('Equity', 'TSLA', 'Tesla, Inc.', 'Consumer Discretionary'),
('Equity', 'NKE', 'NIKE, Inc.', 'Consumer Discretionary'),
('Equity', 'HD', 'The Home Depot, Inc.', 'Consumer Discretionary'),
('Equity', 'GM', 'General Motors Company', 'Consumer Discretionary'),
('Equity', 'XOM', 'Exxon Mobil Corporation', 'Energy'),
('Equity', 'CVX', 'Chevron Corporation', 'Energy'),
('Equity', 'SLB', 'Schlumberger Limited', 'Energy'),
('Equity', 'COP', 'ConocoPhillips', 'Energy'),
('Equity', 'EOG', 'EOG Resources, Inc.', 'Energy'),
('ETF', 'SPY', 'SPDR S&P 500 ETF Trust','US Equity'),
('ETF', 'VTI', 'Vanguard Total Stock Market ETF', 'Global Equity'),
('ETF', 'QQQ', 'Invesco QQQ Trust', 'Nasdaq Equities'),
('ETF', 'EEM', 'iShares MSCI Emerging Markets ETF', 'Emerging Markets Equity'),
('ETF', 'VEA', 'Vanguard FTSE Developed Markets ETF', 'Non US Developed Equity'),
('Currency', 'EURUSD=X', 'Euro to US Dollar', 'Euro'),
('Currency', 'USDJPY=X', 'US Dollar to Japanese Yen', 'Japanese Yen'),
('Currency', 'GBPUSD=X', 'British Pound to US Dollar', 'British Pound'),
('Currency', 'AUDUSD=X', 'Australian Dollar to US Dollar', 'Australlian Dollar'),
('Currency', 'NZDUSD=X', 'New Zealand Dollar to US Dollar', 'New Zealand Dollar'),
('Currency', 'USDCAD=X', 'US Dollar to Canadian Dollar', 'Canadian Dollar'),
('Currency', 'USDCHF=X', 'US Dollar to Swiss Franc', 'Swiss Franc'),
('Currency', 'USDNOK=X', 'US Dollar to Norwegian Krone', 'Norwegian Krone'),
('Currency', 'USDSEK=X', 'US Dollar to Swedish Krona', 'Swedish Krona'),
('Cryptocurrency', 'BTC-USD', 'Bitcoin', 'Cryptocurrency'),
('Cryptocurrency', 'ETH-USD', 'Ethereum', 'Cryptocurrency'),
('Cryptocurrency', 'XRP-USD', 'Ripple', 'Cryptocurrency'),
('Cryptocurrency', 'LTC-USD', 'Litecoin', 'Cryptocurrency'),
('Cryptocurrency', 'BCH-USD', 'Bitcoin Cash', 'Cryptocurrency');
