INSERT INTO [PRACTICE2].[Assets] (Asset_Type, Symbol, Asset_Name, Industry)
VALUES 
('Equity', 'AAPL', 'Apple Inc.', 'Technology'),
('Equity', 'MSFT', 'Microsoft Corporation', 'Technology'),
('Equity', 'GOOGL', 'Alphabet Inc.', 'Technology'),
('Equity', 'NVDA', 'NVIDIA Corporation', 'Technology'),
('Equity', 'AMD', 'Advanced Micro Devices, Inc.', 'Technology'),
('Equity', 'JPM', 'JPMorgan Chase & Co.', 'Financial Services'),
('Equity', 'BAC', 'Bank of America Corporation', 'Financial Services'),
('Equity', 'GS', 'Goldman Sachs Group, Inc.', 'Financial Services'),
('Equity', 'MS', 'Morgan Stanley', 'Financial Services'),
('Equity', 'C', 'Citigroup Inc.', 'Financial Services'),
('Equity', 'JNJ', 'Johnson & Johnson', 'Healthcare'),
('Equity', 'PFE', 'Pfizer Inc.', 'Healthcare'),
('Equity', 'MRK', 'Merck & Co., Inc.', 'Healthcare'),
('Equity', 'ABBV', 'AbbVie Inc.', 'Healthcare'),
('Equity', 'GILD', 'Gilead Sciences, Inc.', 'Healthcare'),
('Equity', 'AMZN', 'Amazon.com, Inc.', 'Consumer Discretionary'),
('Equity', 'TSLA', 'Tesla, Inc.', 'Consumer Discretionary'),
('Equity', 'NKE', 'NIKE, Inc.', 'Consumer Discretionary'),
('Equity', 'HD', 'The Home Depot, Inc.', 'Consumer Discretionary'),
('Equity', 'GM', 'General Motors Company', 'Consumer Discretionary'),
('Equity', 'XOM', 'Exxon Mobil Corporation', 'Energy'),
('Equity', 'CVX', 'Chevron Corporation', 'Energy'),
('Equity', 'SLB', 'Schlumberger Limited', 'Energy'),
('Equity', 'COP', 'ConocoPhillips', 'Energy'),
('Equity', 'EOG', 'EOG Resources, Inc.', 'Energy');