INSERT INTO [PRACTICE2].[Assets] (Asset_Type, Symbol, Industry)
VALUES 
('Equity', 'AAPL', 'Technology'),
('Equity', 'MSFT', 'Technology'),
('Equity', 'GOOGL', 'Technology'),
('Equity', 'NVDA', 'Technology'),
('Equity', 'AMD', 'Technology'),
('Equity', 'JPM', 'Financial Services'),
('Equity', 'BAC', 'Financial Services'),
('Equity', 'GS', 'Financial Services'),
('Equity', 'MS', 'Financial Services'),
('Equity', 'C', 'Financial Services'),
('Equity', 'JNJ', 'Healthcare'),
('Equity', 'PFE', 'Healthcare'),
('Equity', 'MRK', 'Healthcare'),
('Equity', 'ABBV', 'Healthcare'),
('Equity', 'GILD', 'Healthcare'),
('Equity', 'AMZN', 'Consumer Discretionary'),
('Equity', 'TSLA', 'Consumer Discretionary'),
('Equity', 'NKE', 'Consumer Discretionary'),
('Equity', 'HD', 'Consumer Discretionary'),
('Equity', 'GM', 'Consumer Discretionary'),
('Equity', 'XOM', 'Energy'),
('Equity', 'CVX', 'Energy'),
('Equity', 'SLB', 'Energy'),
('Equity', 'COP', 'Energy'),
('Equity', 'EOG', 'Energy');
